host: "localhost" 
port: "8000"
secure: "n"
dbFileName: "/home/clay/ferguson/chat-db/quanta-chat.db"
adminPublicKey: "0357b752ea2b1bcc0365efa73ab0d573f1c27a948aa256394f991c8c09d8edb7df"
desktopMode: "y"
defaultPlugin: "chat"

plugins:
  - name: "Callisto"
    key: "chat"
  - name: "Quanta"
    key: "docs"

# Public folders configuration - array of folder objects with name and path
public-folders:
  - name: "Doc Root"
    key: "root"
    path: "/home/clay/ferguson/A-doc-root-dev"
  
