
# Public folders configuration - array of folder objects with name and path
public-folders:    
  - name: "User Guide"
    key: "user-guide"
    path: "/home/clay/ferguson/quanta-chat/public/user-guide"
