host: "localhost"
port: "8008"
secure: "n"
adminPublicKey: "0357b752ea2b1bcc0365efa73ab0d573f1c27a948aa256394f991c8c09d8edb7df"
desktopMode: "y"
defaultPlugin: "docs"

plugins:
  - name: "Callisto"
    key: "chat"
  - name: "Quanta"
    key: "docs"

# Public folders configuration - array of folder objects with name and path
public-folders:
  - name: "Doc Root"
    key: "root"
    path: "/home/clay/ferguson/A-doc-root"
    