host: "chat.quanta.wiki"
port: "443"
secure: "y"
dbFileName: "/home/clay/db/quanta-chat.db"
adminPublicKey: "0357b752ea2b1bcc0365efa73ab0d573f1c27a948aa256394f991c8c09d8edb7df"
certPath: "/etc/letsencrypt/live/chat.quanta.wiki"
desktopMode: "n"
defaultPlugin: "chat"

plugins:
  - name: "Callisto"
    key: "chat"
 

