host: "0.0.0.0"
# NOTE: This is an internal port number, not the external as mapped in docker-compose-local.yaml
port: "8000"
secure: "n"
adminPublicKey: "0357b752ea2b1bcc0365efa73ab0d573f1c27a948aa256394f991c8c09d8edb7df"
desktopMode: "y"
defaultPlugin: "docs"

plugins:
  - name: "Quanta"
    key: "docs"

# Public folders configuration - array of folder objects with name and path
public-folders:
  - name: "Doc Root"
    key: "root"
    path: "/home/clay/ferguson/A-doc-root"
    