host: "0.0.0.0" 
clientHost: "localhost"  # This is the host that the client will connect to, typically localhost in development
# NOTE: This is an internal port number, not the external as mapped in docker-compose-dev.yaml
port: "8000"
secure: "n"
adminPublicKey: "0357b752ea2b1bcc0365efa73ab0d573f1c27a948aa256394f991c8c09d8edb7df"
desktopMode: "y"
defaultPlugin: "chat"

plugins:
  - name: "Callisto"
    key: "chat"
  - name: "Quanta"
    key: "docs"

# Public folders configuration - array of folder objects with name and path
public-folders:
  - name: "Users"
    key: "usr" # warning: this value is hardcoded in places in the code.
    path: "/"
    type: "vfs"  # Type can be 'lfs' for Linux file system or 'vfs' for virtual PostregreSQL file system
    # Accessable at: http://localhost:8000/doc/pgroot
  
