services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=quanta
      - POSTGRES_USER=quanta
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # NOTE: Quanta volumes are stored one level up from the current directory
      - ../quanta-volumes/dev/postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quanta -d quanta"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    # Example: Use `docker-compose --profile pgadmin ...` to enable this service
    profiles: ["pgadmin"]
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dev
    # Note: This is linux UserId:GroupID, and NOT related to port numbers. 
    user: "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      # Disable pgAdmin logging completely
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=60
      - PGADMIN_CONFIG_FILE_LOG_LEVEL=60
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - GUNICORN_ACCESS_LOGFILE=/dev/null
      - PGADMIN_DISABLE_POSTFIX=True
    volumes:
      # NOTE: Quanta volumes are stored one level up from the current directory
      - ../quanta-volumes/dev/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: "none"

  quanta-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: quanta-dev
    ports:
      - "8000:8000"
    volumes:
      # Mount document root if it exists
      - /home/clay/ferguson/A-doc-root-dev:/home/clay/ferguson/A-doc-root-dev:ro
    environment:
      - CONFIG_FILE=./docker-config-dev.yaml
      - QUANTA_DEV=true
      # PostgreSQL connection info for the app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=quanta
      - POSTGRES_USER=quanta
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # Keep container running and show logs
    stdin_open: true
    tty: true
