version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quanta-postgres
    environment:
      - POSTGRES_DB=quanta
      - POSTGRES_USER=quanta_user
      - POSTGRES_PASSWORD=quanta_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quanta_user -d quanta"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: quanta-pgadmin
    user: "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@quanta.dev
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
      # Disable pgAdmin logging completely
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=60
      - PGADMIN_CONFIG_FILE_LOG_LEVEL=60
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - GUNICORN_ACCESS_LOGFILE=/dev/null
      - PGADMIN_DISABLE_POSTFIX=True
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: "none"

  quanta-app:
    build: .
    container_name: quanta-dev
    ports:
      - "8000:8000"
    volumes:
      # Mount database directory so data persists
      - ./data:/app/data
      # Mount document root if it exists
      - /home/clay/ferguson/A-doc-root-dev:/home/clay/ferguson/A-doc-root-dev:ro
      # Mount chat database directory
      - /home/clay/ferguson/chat-db:/home/clay/ferguson/chat-db
    environment:
      - CONFIG_FILE=./config-dev.yaml
      - QUANTA_DEV=true
      # PostgreSQL connection info for the app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=quanta
      - POSTGRES_USER=quanta_user
      - POSTGRES_PASSWORD=quanta_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # Keep container running and show logs
    stdin_open: true
    tty: true
