version: '3.8'

services:
  # Syslog simulator using a Python script 
  # NOTE: We're not using this simulator in Quanta, we're using the actual Quanta logs (monitoring logs in `[quanta project_root]/dist/server/logs`)
  # logs-file:
  #   image: python:${PYTHON_VERSION:-3.11-slim}
  #   container_name: logs-file
  #   volumes:
  #     - ./main.py:/main.py  # Syslog simulator script
  #     - ./logs:/logs  # Directory to store the logs
  #   depends_on:
  #     - alloy
  #   command: ["python3", "/main.py"]
  

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.10.0}
    ports:
      - 12345:12345
      - 4318:4318
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /home/clay/ferguson/quanta/dist/server/logs:/temp/logs
      - /home/clay/ferguson/grafana-database/alloy:/var/lib/alloy/data
    command: run --server.http.listen-addr=0.0.0.0:12345 --stability.level=experimental  --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki

  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.2}
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - /home/clay/ferguson/grafana-database/loki:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.0.2}
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3000:3000/tcp
    volumes:
      - /home/clay/ferguson/grafana-database/grafana:/var/lib/grafana
    entrypoint:
       - sh
       - -euc
       - |
         mkdir -p /etc/grafana/provisioning/datasources
         cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
         apiVersion: 1
         datasources:
         - name: Loki
           type: loki
           access: proxy
           orgId: 1
           url: http://loki:3100
           basicAuth: false
           isDefault: false
           version: 1
           editable: false
         EOF
         /run.sh
