version: '3.8'

services:

  alloy:
    container_name: alloy-${GRAFANA_ENV_SUFFIX}
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.10.0}
    ports:
      - ${ALLOY_HTTP_PORT}:12345
      - ${ALLOY_OTLP_PORT}:4318
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ${GRAFANA_LOGS_SOURCE_DIR}:/temp/logs
      - ${GRAFANA_DB_BASE_DIR}/alloy:/var/lib/alloy/data
    command: run --server.http.listen-addr=0.0.0.0:12345 --stability.level=experimental  --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki

  loki:
    container_name: loki-${GRAFANA_ENV_SUFFIX}
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.2}
    networks:
      default:
        aliases:
          - loki
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ${GRAFANA_DB_BASE_DIR}/loki:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    container_name: grafana-${GRAFANA_ENV_SUFFIX}
    image: grafana/grafana:${GRAFANA_VERSION:-12.0.2}
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - ${GRAFANA_PORT}:3000/tcp
    volumes:
      - ${GRAFANA_DB_BASE_DIR}/grafana:/var/lib/grafana
    entrypoint:
       - sh
       - -euc
       - |
         mkdir -p /etc/grafana/provisioning/datasources
         cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
         apiVersion: 1
         datasources:
         - name: Loki
           type: loki
           access: proxy
           orgId: 1
           url: http://loki:3100
           basicAuth: false
           isDefault: false
           version: 1
           editable: false
         EOF
         /run.sh
